Implement Initial API Testing Framework for TeamCity
avtikhomirova/teamcity-tests pull request #1
Opened 2023-12-10 06:56 UTC by avtikhomirova

1st iteration

1. Framework Structure: Implemented a comprehensive testing framework covering all essential components.

2. Project Creation Tests: Basic and advanced scenarios including maximum allowed name and ID. Child project creation.
Boundary value analysis.
Negative tests for invalid names, IDs, parent projects, and duplicate projects.

3. Build Configuration Tests: Standard creation process and advanced scenarios with maximum allowed name and ID. Boundary value analysis.
Negative tests for invalid names, IDs, projects, and duplicate build configurations.

2023-12-12 08:56 UTC, AlexPshe requested changes
Привет!

Большое спасибо за качественное выполнение задания!

Я добавила несколько комментов по улучшению - нужно пофиксить их за неделю и будет зачтено ⚡️

2023-12-12 08:56 UTC, AlexPshe commented on .idea/.gitignore
Папку .idea не нужно коммитить, она автоматически создается IDE и хранит IDE настройки 🙌

2023-12-12 08:56 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConnfigurationTest.java
> +                .body(Matchers.containsString("When creating a build type, non empty name should be provided"));
Ошибки можно вынести в отдельный Errors статический класс и сделать константами 🙌

2023-12-12 08:56 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConnfigurationTest.java
> +                .body(Matchers.containsString("The build configuration / template ID \""+ testData.getBuildType().getId() +"\" is already used by another configuration or template"));
Можно реализовать format для более красивой параметризации строки:
https://stackoverflow.com/questions/17364632/java-generating-strings-with-placeholders

2023-12-14 00:22 UTC, avtikhomirova commented on .idea/.gitignore
Спасибо. добавила в .gitignore

2023-12-14 00:22 UTC, avtikhomirova commented on src/test/java/com/example/teamcity/api/BuildConnfigurationTest.java
> +                .body(Matchers.containsString("When creating a build type, non empty name should be provided"));
Done

2023-12-14 00:22 UTC, avtikhomirova commented on src/test/java/com/example/teamcity/api/BuildConnfigurationTest.java
> +                .body(Matchers.containsString("The build configuration / template ID \""+ testData.getBuildType().getId() +"\" is already used by another configuration or template"));
Done

2023-12-17 14:23 UTC, AlexPshe approved these changes
Отлично, все зачтено!

2023-12-17 18:52 UTC, merged