Uitests
avtikhomirova/teamcity-tests pull request #2
Opened 2023-12-17 19:14 UTC by avtikhomirova

1. New UI tests CreateNewBuildConfigurationTest and CreateNewProjectTest. Both Positive and Negative scenarios.
2. Changed Random data generation
3. Add allProjects method in CheckedProject and UncheckedProject
4. Add Projects model

!!! I tried to make an API check in the test CreateNewProjectTest, but I don't think it's a proper variant. Hope to have some comments for improvements.

2023-12-29 19:38 UTC, AlexPshe requested changes
Привет! 

Спасибо за выполненное ДЗ, все гуд, но нужно пофиксить комменты до 10 января и зачтем за сданное 🔥

С наступающим! 🎄

2023-12-29 19:38 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewBuildConfigurationTest.java
> +                .getBuildTypes()
Огонь! Теперь в конце нужно проверить, что проект успешно создался на уровне API 🙌

2023-12-29 19:38 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        if (foundProject.isPresent()) {
Это же ассертом должно быть, если нет проекта, то падаем, так как тест не выполняется?

2023-12-29 19:38 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        new ProjectsPage().open()
Тут в API проверить, что проект не создался

2024-01-04 23:04 UTC, avtikhomirova commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        if (foundProject.isPresent()) {
Да, поправила

2024-01-04 23:39 UTC, avtikhomirova commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        new ProjectsPage().open()
Done

2024-01-05 02:18 UTC, avtikhomirova commented on src/test/java/com/example/teamcity/ui/CreateNewBuildConfigurationTest.java
> +                .getBuildTypes()
Я так поняла, что тут опечатка. Тут нужна проверка на уровне API создалась ли BuildConfiguration. Ее добавила.

2024-01-21 13:56 UTC, AlexPshe approved these changes
Отлично, теперь все огонь! 🔥

2024-01-21 13:56 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewBuildConfigurationTest.java
> +                .getBuildTypes()
Да-да я имела в виду buildConfig

2024-01-21 22:24 UTC, merged